sensors:
- name: top_kinect
  type: kinect
  source: /sergio/top_kinect/rgbd
  frame_id: /sergio/top_kinect/openni_rgb_optical_frame
  visualize: 0
  voxel_size: 0.02
  max_range: 2.0
  clearing_padding_fraction: 0.05
  normal_k_search: 15
  association_modules:
  - type: PointNormal
    parameters:
        association_correspondence_distance: 0.3
        position_weight: 2.0
        normal_weight: 1.0
        render_width: 320
        render_max_range: 2.2
        render_voxel_size: 0.02
        normal_k_search: 15
        visualize: 0
  - type: PolygonHeight
    parameters:
        max_range: 2.0
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0
  segmentation_modules:
  - type: EuclideanClustering
    parameters:
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0

visualize: 1
world_name: robotics_testlabs

perception:
    fit_shapes: 1
    model_list: all_models.yml
    modules:
#    -  lib: libsize_matcher.so
#    -  lib: libodu_finder.so
#    -  lib: libhuman_contour_matcher.so
#    -  lib: libface_detector.so
#    -  lib: libtype_aggregator.so

plugins:
- name: gui_server
  lib: libed_gui_server_plugin.so
  parameters:
      robot_name: sergio
#- name: builder
#  lib: libed_builder_plugin.so
- name: obstacle_grid_publisher
  lib: libed_occupancy_grid_publisher_plugin.so
  parameters:
      frequency: 10
      resolution: 0.05
      topic: /ed_map
      frame_id: /map
      sim_time: 1.0
      object_persistence_time: 10
- name: loc_grid_publisher
  lib: libed_occupancy_grid_publisher_plugin.so
  parameters:
      frequency: 1
      resolution: 0.025
      topic: /ed_loc_map
      frame_id: /map
      specifier: localizable
      sim_time: 0.0
- name: tf_publisher
  lib: libed_tf_publisher_plugin.so
  parameters:
      root_frame_id: /map
#- name: amigo_plugin
#  lib: ed_robot_plugin
#  parameters:
#      robot_name: amigo
#      urdf_rosparam: /amigo/robot_description
#      joint_topics:
#          - topic: /amigo/torso/measurements
#- name: hello_world2
#  lib: libed_hello_world_plugin.so
#  parameters:
#      text: "Hello world! 2"
#- name: hello_world3
#  lib: libed_hello_world_plugin.so
#  parameters:
#      text: "Hello world! 3"
- name: localization
  lib: libed_localization_plugin.so
  parameters:
      initial_pose_topic: /sergio/initialpose
      num_particles: 500
      initial_pose:
          x: $(env ROBOT_INIT_X)
          y: $(env ROBOT_INIT_Y)
          rz: $(env ROBOT_INIT_PHI)    
      laser_model:
          topic: /sergio/base_laser/scan
          num_beams: 100
          z_hit: 0.95
          sigma_hit: 0.2
          z_short: 0.1
          z_max: 0.05
          z_rand: 0.05
          lambda_short: 0.1
          range_max: 10
          min_particle_distance: 0.01
          min_particle_rotation_distance: 0.02
      odom_model:
          map_frame: map
          odom_frame: /sergio/odom
          base_link_frame: /sergio/base_link
          alpha1: 0.05   # rot -> trans + strafe
          alpha2: 0.5    # trans -> rot
          alpha3: 0.5    # trans -> trans
          alpha4: 0.5    # rot -> rot
          alpha5: 0.5    # trans -> strafe


gui:
    enabled: 1
    srv_get_measurements: /ed/gui/get_measurements
    srv_set_label: /ed/gui/set_label
    srv_raise_event: /ed/gui/raise_event
    srv_get_command: /ed/gui/get_gui_command
    map_image_topic: /ed/gui/map_image
    map_image_width: 500
    map_image_height: 500
    world_width: 11.0
    world_height: 11.0
    cam_x: 4.5
    cam_y: 4.4
    cam_z: 10.0

